name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest

        uses: proyecto-chaucha/chaucha-gha-opreturn@master
        with:
          privkey: "${{secret.PRIVKEY}}"
          pubkey: "${{secret.PUBKEY}}"
          sendkey: "${{secret.SENDKEY}}"
          message: "repo: ${GITHUB_REPOSITORY}; branch: ${GITHUB_REF}; commit: ${GITHUB_SHA}"

      # Certify commit using notes
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin "refs/notes/*:refs/notes/*"
          git notes append -m "repo: ${GITHUB_REPOSITORY}; branch: ${GITHUB_REF}; commit: ${GITHUB_SHA}; tx: ${steps.selftest.outputs.response}"
          git push origin "refs/notes/*"

      # - name: Check outputs
      #   run: |
      #     test "${{ steps.selftest.outputs.response }}" == "Hello world"
